"""Types for the pinned Platform SDK's existing public methods. | 平台公开方法类型投影。"""

from enum import Enum
from pathlib import Path
from typing import Any

class ArtifactKind(Enum):
    MODEL = "model"

class ArtifactError(RuntimeError): ...
class ArtifactIntegrityError(ArtifactError): ...

class ArtifactRef:
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ArtifactRef: ...
    def to_dict(self) -> dict[str, Any]: ...

class StagedArtifact: ...

class LocalArtifactProvider:
    root: Path
    def __init__(self, root: str | Path, *, chunk_size: int = ...) -> None: ...
    def publish_portable_directory(self, source: str | Path, *, kind: ArtifactKind = ...) -> ArtifactRef: ...
    def stage(self, artifact_ref: ArtifactRef, destination: str | Path) -> StagedArtifact: ...
