# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiInferenceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPredict = channel.stream_stream(
                '/cy.llm.AiInference/StreamPredict',
                request_serializer=ai__service__pb2.StreamPredictRequest.SerializeToString,
                response_deserializer=ai__service__pb2.StreamPredictResponse.FromString,
                _registered_method=True)
        self.Control = channel.unary_unary(
                '/cy.llm.AiInference/Control',
                request_serializer=ai__service__pb2.ControlMessage.SerializeToString,
                response_deserializer=ai__service__pb2.ControlMessage.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/cy.llm.AiInference/Health',
                request_serializer=ai__service__pb2.WorkerHealthRequest.SerializeToString,
                response_deserializer=ai__service__pb2.WorkerHealthResponse.FromString,
                _registered_method=True)


class AiInferenceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamPredict(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=ai__service__pb2.StreamPredictRequest.FromString,
                    response_serializer=ai__service__pb2.StreamPredictResponse.SerializeToString,
            ),
            'Control': grpc.unary_unary_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=ai__service__pb2.ControlMessage.FromString,
                    response_serializer=ai__service__pb2.ControlMessage.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=ai__service__pb2.WorkerHealthRequest.FromString,
                    response_serializer=ai__service__pb2.WorkerHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cy.llm.AiInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cy.llm.AiInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiInference:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cy.llm.AiInference/StreamPredict',
            ai__service__pb2.StreamPredictRequest.SerializeToString,
            ai__service__pb2.StreamPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiInference/Control',
            ai__service__pb2.ControlMessage.SerializeToString,
            ai__service__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cy.llm.AiInference/Health',
            ai__service__pb2.WorkerHealthRequest.SerializeToString,
            ai__service__pb2.WorkerHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
