"""
┌─────────────────────────────────────────────────────────────────────┐
│  make_lora_fixture.py                                                │
│  Module: reactor_product.scripts                                     │
│  Role: Create reproducible nonzero Qwen2 LoRA weights without training.│
│  模块职责：制作真实推理验收用 LoRA 制品；不执行训练或复制基础模型权重。      │
└─────────────────────────────────────────────────────────────────────┘
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import re
import struct
from pathlib import Path
from typing import Any


def make_fixture(base: Path, repository: str, revision: str, output: Path) -> dict[str, Any]:
    """Write standard PEFT files using deterministic CPU data, with no optimizer. | 非训练制品。"""
    if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
        raise ValueError("Expected an immutable Hugging Face model source")
    if not re.fullmatch(r"[0-9a-f]{40}", revision):
        raise ValueError("An exact 40-character base revision is required")
    config = json.loads((base / "config.json").read_text())
    if config.get("model_type") != "qwen2":
        raise ValueError("This acceptance fixture only supports the selected Qwen2 architecture")
    hidden = int(config["hidden_size"])
    layers = int(config["num_hidden_layers"])
    heads = int(config["num_attention_heads"])
    kv_heads = int(config["num_key_value_heads"])
    if min(hidden, layers, heads, kv_heads) < 1 or hidden % heads:
        raise ValueError("Invalid attention dimensions")
    output.mkdir(parents=True, exist_ok=False)
    rank = 8
    rng = random.Random(20260906)
    tensors: dict[str, Any] = {"__metadata__": {"format": "pt"}}
    chunks: list[bytes] = []
    offset = 0
    for layer in range(layers):
        for module, width in (("q_proj", hidden), ("v_proj", kv_heads * hidden // heads)):
            for matrix, shape, scale in (("A", [rank, hidden], 0.02), ("B", [width, rank], 0.01)):
                name = (
                    f"base_model.model.model.layers.{layer}.self_attn.{module}.lora_{matrix}.weight"
                )
                count = shape[0] * shape[1]
                values = [rng.gauss(0, scale) for _ in range(count)]
                data = struct.pack(f"<{count}f", *values)
                tensors[name] = {
                    "dtype": "F32",
                    "shape": shape,
                    "data_offsets": [offset, offset + len(data)],
                }
                chunks.append(data)
                offset += len(data)
    header = json.dumps(tensors, separators=(",", ":"), sort_keys=True).encode()
    header += b" " * (-len(header) % 8)
    weights = struct.pack("<Q", len(header)) + header + b"".join(chunks)
    (output / "adapter_model.safetensors").write_bytes(weights)
    adapter_config = {
        "base_model_name_or_path": repository,
        "revision": revision,
        "peft_type": "LORA",
        "task_type": "CAUSAL_LM",
        "inference_mode": True,
        "r": rank,
        "lora_alpha": 16,
        "lora_dropout": 0.0,
        "target_modules": ["q_proj", "v_proj"],
        "bias": "none",
        "modules_to_save": None,
        "use_dora": False,
        "use_rslora": False,
    }
    (output / "adapter_config.json").write_text(json.dumps(adapter_config, indent=2) + "\n")
    (output / "README.md").write_text(
        "# Deterministic LoRA serving fixture / 确定性 LoRA 推理验收制品\n\n"
        "These nonzero weights were generated by make_lora_fixture.py with Python 3.12, "
        "seed 20260906. They are synthetic inference data, have not been trained, and "
        "carry no quality claim. No base weights, dataset, optimizer, or TrainingRun "
        "is included. The base repository and exact revision are in adapter_config.json.\n\n"
        "本制品包含标准 PEFT 配置和非零 safetensors 权重,用于实际 LoRA 载入及数值差异证明。"
        "没有训练、训练数据或虚构的训练来源;不宣称模型质量改善。\n"
    )
    return {
        "generator": "make_lora_fixture.py",
        "seed": 20260906,
        "trained": False,
        "baseSource": {"repository": repository, "revision": revision},
        "tensorCount": len(tensors) - 1,
        "weightBytes": len(weights),
        "weightSha256": hashlib.sha256(weights).hexdigest(),
        "generatorSha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    }


def main() -> None:
    """Generate only the requested fixture directory. | 只写入指定的新目录。"""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-directory", required=True, type=Path)
    parser.add_argument("--base-repository", required=True)
    parser.add_argument("--base-revision", required=True)
    parser.add_argument("--output-directory", required=True, type=Path)
    args = parser.parse_args()
    print(
        json.dumps(
            make_fixture(
                args.base_directory, args.base_repository, args.base_revision, args.output_directory
            ),
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
